[book]
authors = ["Francisco Perez-Sorrosal"]
language = "en"
multilingual = false
src = "src"
title = "Quantum Computing Resources"

[output.html]
mathjax-support = true
theme = "theme"

[preprocessor.bib]
bibliography = "biblio.bib"
renderer = ["html"]
